#define PIN_EXT_LIGHT_SENSOR			2
#define PIN_EXT_BUZZER						3
#define PIN_EXT_BUTTON						4
#define PIN_EXT_LED_YELLOW				5
#define PIN_EXT_LED_RED						6
#define PIN_EXT_LED_GREEN					7
#define PIN_EXT_LED_BLUE					8
#define PIN_EXT_SWITCH						9
#define PIN_EXT_SCL								10
#define PIN_EXT_SDA								11
#define PIN_INT_LED_RED						12
#define PIN_INT_LED_GREEN					13
#define PIN_INT_LED_BLUE					14
#define PIN_INT_LED_BAR_0					15
#define PIN_INT_LED_BAR_1					16
#define PIN_INT_LED_BAR_2					17
#define PIN_INT_LED_BAR_3					18
#define PIN_INT_LED_BAR_4					19
#define PIN_INT_LED_BAR_5					20